OjayFood/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OjayFood.Areas.Admin.Models;
using OjayFood.Domain.Concrete;
using OjayFood.Domain.Entities;

namespace OjayFood.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        EFImageRepository efImageRepo = new EFImageRepository();

        public ActionResult Index()
        {
            ImageViewModel model = new ImageViewModel
            {
                Images = efImageRepo.GetAllImages
            };
            return View();
        }

        [HttpPost]
        public JsonResult UploadImages()
        {
            JsonResult result = new JsonResult();

            var imgList = new List<Image>();



            var files = Request.Files;

            for (int i = 0; i < files.Count; i++)
            {
                var image = files[i];

                var fileName = Guid.NewGuid() + Path.GetExtension(image.FileName);
                var filePath = Server.MapPath("~/Images/Site/") + fileName; 

                image.SaveAs(filePath);

                var dbImage = new Image();
                dbImage.URL = fileName;

                if (efImageRepo.SaveImage(dbImage))
                {
                    imgList.Add(dbImage);
                }
            }

            result.Data = imgList;

            return result;
        }
    }
}

OjayFood/Areas/Admin/Controllers/ProductController.cs
using System;
using OjayFood.Domain.Concrete;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OjayFood.Areas.Admin.Models;
using OjayFood.Domain.Abstract;
using OjayFood.Domain.Entities;
using OjayFood.Models;

namespace OjayFood.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
    
    public ProductController() { }
        
        private IProductRepository _prodRepo;
        public int PageSize = 5;

        public ProductController(IProductRepository productRepository)
        {
            this._prodRepo = productRepository;
        }


        public ActionResult Index(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = _prodRepo.GetAllProducts
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),


                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        _prodRepo.GetAllProducts.Count() :
                        _prodRepo.GetAllProducts.Where(e => e.Category == category).Count()
                },
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int? Id)
        {
            ProductActionViewModel model = new ProductActionViewModel();

            if (Id.HasValue) //we are trying to edit a record
            {
                var product = _prodRepo.GetProductById(Id.Value);

                model.Id = product.Id;
                model.Name = product.Name;
                model.Price = product.Price;
                model.Mfg_Date = product.Mfg_Date;
                model.Exp_Date = product.Exp_Date;
                model.Category = product.Category;
                model.Description = product.Description;

                model.ProductImages = _prodRepo.GetImagesByProductID(product.Id);
            }
            
            return PartialView("_Action", model);
        }

        [HttpPost]
        public JsonResult Action(ProductActionViewModel model)
        {

            JsonResult json = new JsonResult();

            var result = false;
            var efImageRepo = new EFImageRepository();
            var list = model.ImageIDs;
            var imgIDs = string.Join(",", list);

            List<int> imageIDs = !string.IsNullOrEmpty(imgIDs) ? model.ImageIDs.Select(x => int.Parse(x)).ToList() : new List<int>();

            var images = efImageRepo.GetImagesByIDs(imageIDs);

            if (model.Id > 0) //we are trying to edit a record
            {
                var product = _prodRepo.GetProductById(model.Id);

                product.Id = model.Id;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Mfg_Date = model.Mfg_Date;
                product.Exp_Date = model.Exp_Date;
                product.Category = model.Category;
                product.Description = model.Description;
                product.ProductURL = images.Select(x => x.URL).FirstOrDefault();

                product.ProductImages.AddRange(images.Select(x => new ProductImage() { ProductID = product.Id, ImageID = x.ID }));
                
                _prodRepo.UpdateProduct(product);
            }
            else //we are trying to create a record
            {
                Product product = new Product();

                //product.Id = model.Id;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Mfg_Date = model.Mfg_Date;
                product.Exp_Date = model.Exp_Date;
                product.Category = model.Category;
                product.Description = model.Description;
                product.ProductURL = images.Select(x => x.URL).FirstOrDefault();


                product.ProductImages = new List<ProductImage>();
                product.ProductImages.AddRange(images.Select(x => new ProductImage() { ProductID = product.Id, ImageID = x.ID }));

                _prodRepo.SaveProduct(product);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Products." };
            }

            return json;
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {

            ProductActionViewModel model = new ProductActionViewModel();

            var product = _prodRepo.GetProductById(Id);

            model.Id = product.Id;

            return PartialView("_Delete", model);
        }


        [HttpPost]
        public JsonResult Delete(ProductActionViewModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var product = _prodRepo.GetProductById(model.Id);

            _prodRepo.DeleteProduct(product);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Product." };
            }

            return json;
        }
    }
}

OjayFood/Areas/Admin/Views/Product/Index.cshtml
@model OjayFood.Areas.Admin.Models.ProductListViewModel


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="~/Areas/Admin/Content/css/styles.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Manage <b>Products</b></h2>
                    </div>
                    <div class="col-sm-6">
                        <a data-href="@Url.Action("Action", "Product")" class="data-btn btn btn-success" data-toggle="modal" data-target="#actionModal"><i class="material-icons">&#xE147;</i> <span>Add New Product</span></a>
                        <a href="#deleteProductModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>
                    </div>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Mfg_Date</th>
                        <th scope="col">Exp_Date</th>
                        <th scope="col">Category</th>
                        <th scope="col">Description</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Products != null)
                    {
                        foreach (var product in Model.Products)
                        {
                            <tr>
                                <td>
                                    @product.Name
                                </td>
                                <td>
                                    @product.Price
                                </td>
                                <td>
                                    @product.Mfg_Date
                                </td>
                                <td>
                                    @product.Exp_Date
                                </td>
                                <td>
                                    @product.Category
                                </td>
                                <td>
                                    @product.Description
                                </td>
                                <td>
                                    <button data-href="@Url.Action("Action", "Product", new { Id = product.Id })" type="button" class="data-btn btn btn-success" data-toggle="modal" data-target="#actionModal"><i class="fa-solid fa-pen mr-1"></i>Edit</button>
                                    <button data-href="@Url.Action("Delete", "Product", new { Id = product.Id })" type="button" class="data-btn btn btn-danger" data-toggle="modal" data-target="#actionModal"><i class="fa-solid fa-trash-can mr-1"></i>Delete</button>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            @*<div class="row">
                    <div class="col col-lg-12">
                        @{
                            Html.RenderPartial("_Listing", Model);
                        }
                    </div>
                </div>*@
        </div>
    </div>
    <!-- Modal HTML -->
    <div id="actionModal" class="modal fade" style="height:auto; width:50%; position:center">
        <div class="modal-dialog" role="document">

        </div>
    </div>

    <!-- Delete Modal HTML -->
    <div id="deleteProductModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Product</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete these Records?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="pager">
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index",
            new { page = x, category = Model.CurrentCategory }))
    </div>

</body>

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
            type: "get",
        })
        .done(function (response) {
            $("#actionModal").html(response);
        });
    });




    $(document).ready(function () {
        // Activate tooltip
        $('[data-toggle="tooltip"]').tooltip();

        // Select/Deselect checkboxes
        var checkbox = $('table tbody input[type="checkbox"]');
        $("#selectAll").click(function () {
            if (this.checked) {
                checkbox.each(function () {
                    this.checked = true;
                });
            } else {
                checkbox.each(function () {
                    this.checked = false;
                });
            }
        });
        checkbox.click(function () {
            if (!this.checked) {
                $("#selectAll").prop("checked", false);
            }
        });
    });



</script>

OjayFood/Areas/Admin/Views/Product/_Action.cshtml
@model OjayFood.Areas.Admin.Models.ProductActionViewModel

@if (Model != null)
{
    <div class="modal-content">
        <form id="actionForm">
            <h5 class="modal-header">
                @if (Model.Id > 0)
                {
                    <span>Edit Product</span>
                }
                else
                {
                    <span>Create Product</span>
                }
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </h5>
            <div class="modal-body">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Product Name" value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <textarea class="form-control" name="Price" placeholder="Enter Product Price">@Model.Price</textarea>
                </div>
                <div class="form-group">
                    <label>Product Manufacture Date</label>
                    <textarea class="form-control" name="Mfg_Date" placeholder="Enter Product Manufacture Date">@Model.Mfg_Date</textarea>
                </div>
                <div class="form-group">
                    <label>Product Expiry Date</label>
                    <textarea class="form-control" name="Exp_Date" placeholder="Enter Product Expiry Date">@Model.Exp_Date</textarea>
                </div>
                <div class="form-group">
                    <label>Category</label>
                    <textarea class="form-control" name="Category" placeholder="Enter Product Category">@Model.Category</textarea>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="Description" placeholder="Enter Product Description">@Model.Description</textarea>
                </div>
                <div class="form-group">
                    <label>Images</label>
                    <input id="selectImages" class="form-control" name="Images" type="file" multiple>
                    <input type="hidden" name="imageIDs" id="imageIDs" value="" />
                </div>
                <div id="imagesArea">
                    @if (Model.ProductImages != null && Model.ProductImages.Count > 0)
                    {
                        foreach (var productImage in Model.ProductImages)
                        {
                            <img src="~/Images/Site/@productImage.Image.URL" class="img-fluid" style="width:200px" onclick="removeMe(this)" data-id="@productImage.ImageID" />
                        }
                    }
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                <input id="actionButton" type="submit" class="btn btn-success" value="Add">
            </div>
        </form>
    </div>
}

<div id="imageTemplate">
    <img src="" class="img-fluid" style="width:200px" onclick="removeMe(this)"/>
</div>

<script>
    $("#actionButton").click(function () {

        var imageIDs = [];
        $("#imagesArea img").each(function () {
            var imgID = $(this).attr("data-id");

            imageIDs.push(imgID);
        });

        $("#imageIDs").val(imageIDs.join());

        $.ajax({
            url:  '@Url.Action("Action", "Product")',
            type: "post",
            data: $("#actionForm").serialize()
        })
        .done(function (response) {
            if (response.Success)
            {
                location.reload();
            }
            else
            {
                $(".errorDiv").html(response.Message);
            }
        });
    });

    $("#selectImages").change(function () {

        var images = this.files;

        var formData = new FormData();

        for (var i = 0; i < images.length; i++) {
            formData.append("Image", images[i]);
        }

        $.ajax({
            url:  '@Url.Action("UploadImages", "Dashboard")',
            type: "post",
            data: formData,
            processData: false,
            contentType: false
        })
        .done(function (response) {
            for (var i = 0; i < response.length; i++) {
                var image = response[i];

                var $imgHTML = $("#imageTemplate").clone();

                $imgHTML.find("img").attr("src", "/Images/Site/" + image.URL);
                $imgHTML.find("img").attr("data-id", image.ID);

                $("#imagesArea").append($imgHTML.html());   
            }            
        });
    });

    function removeMe(element) {
        element.remove();
    }
</script>

OjayFood/Areas/Admin/Views/Product/_Delete.cshtml
@model OjayFood.Areas.Admin.Models.ProductActionViewModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <span>Delete Product</span>
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="Id" value="@Model.Id" />
            </form>
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete this Product?
            </div>
        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-danger"><i class="fa-solid fa-trash-can mr-1"></i>Delete</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-xmark mr-1"></i>Close</button>
        </div>
    </div>
}


<script>
    $("#actionButton").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Product")',
            type: 'post',
            data: $("#actionForm").serialize()
        })
        .done(function (response) {
            if (response.Success)
            {
                window.location.href = "@Url.Action("Index", "Product")";
            }
            else
            {
                $(".errorDiv").html(response.Message);
            }
        });
    });
</script>

OjayFood/Areas/Admin/Views/Product/_Listing.cshtml
@model OjayFood.Areas.Admin.Models.ProductListViewModel


@if (Model != null && Model.Products != null && Model.Products.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Mfg_Date</th>
                <th scope="col">Exp_Date</th>
                <th scope="col">Category</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>
                            @product.Name
                        </td>
                        <td>
                            @product.Price
                        </td>
                        <td>
                            @product.Mfg_Date
                        </td>
                        <td>
                            @product.Exp_Date
                        </td>
                        <td>
                            @product.Category
                        </td>
                        <td>
                            <button data-href="@Url.Action("Action", "Product", new { Id = product.Id })" type="button" class="data-btn btn btn-success" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fa-solid fa-pen mr-1"></i>Edit</button>
                            <button data-href="@Url.Action("Delete", "Product", new { Id = product.Id })" type="button" class="data-btn btn btn-danger" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fa-solid fa-trash-can mr-1"></i>Delete</button>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No records exist.
    </div>
}