OjayFood/Areas/Admin/Controllers/PaymentTypeController.cs
using OjayFood.Areas.Admin.Models;
using OjayFood.Domain.Abstract;
using OjayFood.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OjayFood.Areas.Admin.Controllers
{
    public class PaymentTypeController : Controller
    {
        PaymentTypeController() { }

        private IPaymentTypeRepository _payTypeRepo;

        public PaymentTypeController(IPaymentTypeRepository repository)
        {
            this._payTypeRepo = repository;
        }

        // GET: Admin/PaymentType
        public ActionResult Index()
        {
            PaymentTypeViewModel model = new PaymentTypeViewModel();

            model.PaymentTypes = _payTypeRepo.GetAllPaymentTypes;

            return View(model);
        }

        public ActionResult Create()
        {
            return View(new PaymentType());
        }

        [HttpPost]
        public ActionResult Create(PaymentType paymentType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _payTypeRepo.SavePaymentType(paymentType);

                    //return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            PaymentType paymentType = _payTypeRepo.GetPaymentType(id);
            return View(paymentType);
        }

        [HttpPost]
        public ActionResult Edit(PaymentType paymentType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _payTypeRepo.UpdatePaymentType(paymentType);

                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(paymentType);
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {

            PaymentTypeActionModel model = new PaymentTypeActionModel();

            var paymentType = _payTypeRepo.GetPaymentType(ID);

            model.Id = paymentType.Id;

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public JsonResult Delete(PaymentTypeActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var paymentType = _payTypeRepo.GetPaymentType(model.Id);

            _payTypeRepo.DeletePaymentType(paymentType.Id);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Department." };
            }

            return json;
        }

    }
}

OjayFood/Areas/Admin/Controllers/ProductController.cs
using System;
using OjayFood.Domain.Concrete;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OjayFood.Areas.Admin.Models;
using OjayFood.Domain.Abstract;
using OjayFood.Domain.Entities;
using OjayFood.Models;

namespace OjayFood.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
    
    public ProductController() { }
        
        private IProductRepository _prodRepo;
        public int PageSize = 5;

        public ProductController(IProductRepository productRepository)
        {
            this._prodRepo = productRepository;
        }


        public ActionResult Index(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = _prodRepo.GetAllProducts
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),


                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        _prodRepo.GetAllProducts.Count() :
                        _prodRepo.GetAllProducts.Where(e => e.Category == category).Count()
                },
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int? Id)
        {
            ProductActionViewModel model = new ProductActionViewModel();

            if (Id.HasValue) //we are trying to edit a record
            {
                var product = _prodRepo.GetProductById(Id.Value);

                model.Id = product.Id;
                model.Name = product.Name;
                model.Price = product.Price;
                model.Mfg_Date = product.Mfg_Date;
                model.Exp_Date = product.Exp_Date;
                model.Category = product.Category;
                model.Description = product.Description;

                model.ProductImages = _prodRepo.GetImagesByProductID(product.Id);
            }
            
            return PartialView("_Action", model);
        }

        [HttpPost]
        public JsonResult Action(ProductActionViewModel model)
        {

            JsonResult json = new JsonResult();

            var result = false;
            var efImageRepo = new EFImageRepository();
            var list = model.ImageIDs;
            var imgIDs = string.Join(",", list);

            List<int> imageIDs = !string.IsNullOrEmpty(imgIDs) ? model.ImageIDs.Select(x => int.Parse(x)).ToList() : new List<int>();

            var images = efImageRepo.GetImagesByIDs(imageIDs);

            if (model.Id > 0) //we are trying to edit a record
            {
                var product = _prodRepo.GetProductById(model.Id);

                product.Id = model.Id;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Mfg_Date = model.Mfg_Date;
                product.Exp_Date = model.Exp_Date;
                product.Category = model.Category;
                product.Description = model.Description;
                product.ProductURL = images.Select(x => x.URL).FirstOrDefault();

                product.ProductImages.AddRange(images.Select(x => new ProductImage() { ProductID = product.Id, ImageID = x.ID }));
                
                _prodRepo.UpdateProduct(product);
            }
            else //we are trying to create a record
            {
                Product product = new Product();

                //product.Id = model.Id;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Mfg_Date = model.Mfg_Date;
                product.Exp_Date = model.Exp_Date;
                product.Category = model.Category;
                product.Description = model.Description;
                product.ProductURL = images.Select(x => x.URL).FirstOrDefault();


                product.ProductImages = new List<ProductImage>();
                product.ProductImages.AddRange(images.Select(x => new ProductImage() { ProductID = product.Id, ImageID = x.ID }));

                _prodRepo.SaveProduct(product);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Products." };
            }

            return json;
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {

            ProductActionViewModel model = new ProductActionViewModel();

            var product = _prodRepo.GetProductById(Id);

            model.Id = product.Id;

            return PartialView("_Delete", model);
        }


        [HttpPost]
        public JsonResult Delete(ProductActionViewModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var product = _prodRepo.GetProductById(model.Id);

            _prodRepo.DeleteProduct(product);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Product." };
            }

            return json;
        }
    }
}

OjayFood/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - OjayFoods</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Areas/Admin/Content/vendor/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/css/styles.css" rel="stylesheet" />

    <script src="https://kit.fontawesome.com/adf95bd522.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Admin/Content/vendor/jquery/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar-->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <i class="fa fa-globe" aria-hidden="true"></i> OjayFoods
            </div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "Product")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-cutlery" aria-hidden="true"></i> Food Products
                </a>
                <a href="@Url.Action("Index", "PaymentType")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-credit-card-blank"></i> Payment Type
                </a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">
                    <i class="fas fa-bars"></i>
                </button>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">
                                <i class="fa-solid fa-house-chimney"></i>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">
                                <i class="fa-solid fa-right-from-bracket mr-1"></i>Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
    }

    <!-- /wrapper -->
    <script src="~/Areas/Admin/Content/vendor/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

</body>
</html>

OjayFood/Areas/Admin/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - OjayFoods</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Areas/Dashboard/Content/Vendor/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Dashboard/Content/css/styles.css" rel="stylesheet" />

    <script src="https://kit.fontawesome.com/adf95bd522.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Dashboard/Content/vendor/jquery/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar-->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <i class="fa-solid fa-hotel mr-1"></i> HMS
            </div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "AccomodationTypes")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-building mr-1"></i> Accomodation Types
                </a>
                <a href="@Url.Action("Index", "AccomodationPackages")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-diagram-project"></i> Accomodation Packages
                </a>
                <a href="@Url.Action("Index", "Accomodation")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-map-pin"></i> Accomodations
                </a>
                <a href="@Url.Action("Index", "Roles")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-users mr-1"></i> Roles
                </a>
                <a href="@Url.Action("Index", "Users")" class="list-group-item list-group-item-action bg-light">
                    <i class="fa-solid fa-users mr-1"></i> Users
                </a>

            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">
                    <i class="fas fa-bars"></i>
                </button>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">
                                <i class="fa-solid fa-right-from-bracket mr-1"></i>Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
    }

    <!-- /wrapper -->
    <script src="~/Areas/Dashboard/Content/Vendor/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

</body>
</html>